version: '3'

services:
  redis:
    image: redis:6.2-alpine
    container_name: redis_container
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-db:/data
volumes:
  redis-db: